### ISSUE TITLE
Consider renaming <Only /> component to <Responsive />

### ISSUE THREAD

**Issue by prince272** [bloczjs/react-responsive#33]

**Comment by Ayc0** [comment]
@prince272 can you explain why do you want this renaming?

**Comment by prince272** [comment]
Because the name of the project is called react-responsive.

**Comment by Ayc0** [comment]
`Only` wasn't renamed because if you read the docs, it is used to only display its children when the viewport matches the breakpoint `<Only on="xs">Hello</Only>`. `<Responsive on="xs">Hello</Responsive>` would be less explanatory on what this component is supposed to behave

**Comment by prince272** [comment]
You're right. I thought of it as well. We can now close the issue.
